// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8kJP0y8op_OsdPyBgaERweDmcyqlfVzE',
    appId: '1:265274889608:web:f953995703e852342dd63d',
    messagingSenderId: '265274889608',
    projectId: 'flutter-test-b2b28',
    authDomain: 'flutter-test-b2b28.firebaseapp.com',
    storageBucket: 'flutter-test-b2b28.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj88SG7QnsuwjsoTg6u4np3VRS0Gt0RGE',
    appId: '1:265274889608:android:20de0c21490db04b2dd63d',
    messagingSenderId: '265274889608',
    projectId: 'flutter-test-b2b28',
    storageBucket: 'flutter-test-b2b28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMzBSjjB4Ae7Kb9KaoGKf9tuGyJAO2iEY',
    appId: '1:265274889608:ios:fef90e6c7a2bbf202dd63d',
    messagingSenderId: '265274889608',
    projectId: 'flutter-test-b2b28',
    storageBucket: 'flutter-test-b2b28.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMzBSjjB4Ae7Kb9KaoGKf9tuGyJAO2iEY',
    appId: '1:265274889608:ios:fef90e6c7a2bbf202dd63d',
    messagingSenderId: '265274889608',
    projectId: 'flutter-test-b2b28',
    storageBucket: 'flutter-test-b2b28.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

}